<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DefaultTdsCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tdsCategories = [
            [
                'section' => '192',
                'category_name' => 'Salary',
                'description' => 'TDS on Salary',
                'rate' => null,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 501,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '192A',
                'category_name' => 'EPF Withdrawal',
                'description' => 'Premature withdrawal from EPF',
                'rate' => 10.00,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 502,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '193',
                'category_name' => 'Interest on Securities',
                'description' => 'Interest on securities paid by government or companies',
                'rate' => 10.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'status' => true,
                'code' => 503,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194',
                'category_name' => 'Dividend',
                'description' => 'Dividend income',
                'rate' => 10.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'code' => 504,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194A',
                'category_name' => 'Bank/Post Office Interest',
                'description' => 'Interest other than securities',
                'rate' => 10.00,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 505,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194B',
                'category_name' => 'Lottery Winnings',
                'description' => 'Winning from lottery or puzzle',
                'rate' => 30.00,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 506,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194BB',
                'category_name' => 'Horse Race Winnings',
                'description' => 'Winning from horse races',
                'rate' => 30.00,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 507,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194C',
                'category_name' => 'Contractor/ Sub-contractor',
                'description' => 'Payment to contractors',
                'rate' => 1.00,
                'type' => 'TDS',
                'applicable_to' => 'Company',
                'code' => 508,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194D',
                'category_name' => 'Insurance Commission',
                'description' => 'Commission on insurance',
                'rate' => 5.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'code' => 509,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194DA',
                'category_name' => 'Life Insurance Maturity',
                'description' => 'Payout on life insurance policies',
                'rate' => 5.00,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 510,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194E',
                'category_name' => 'Non-resident Entertainers',
                'description' => 'Non-resident sportsmen/entertainers',
                'rate' => 20.00,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 511,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194H',
                'category_name' => 'Commission or Brokerage',
                'description' => 'Brokerage and commission payments',
                'rate' => 5.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'code' => 512,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194I',
                'category_name' => 'Rent (Land/Building)',
                'description' => 'Rent for land or building',
                'rate' => 10.00,
                'type' => 'TDS',
                'applicable_to' => 'Company',
                'code' => 513,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194IA',
                'category_name' => 'Property Sale >= ₹50L',
                'description' => 'Transfer of immovable property',
                'rate' => 1.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'code' => 514,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194J',
                'category_name' => 'Professional Services',
                'description' => 'Fees for professional services',
                'rate' => 10.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'code' => 515,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194K',
                'category_name' => 'Mutual Fund Income',
                'description' => 'TDS on income from mutual funds',
                'rate' => 10.00,
                'type' => 'TDS',
                'applicable_to' => 'Individual',
                'code' => 516,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194N',
                'category_name' => 'Cash Withdrawal > ₹1 Cr',
                'description' => 'TDS on large cash withdrawal',
                'rate' => 2.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'code' => 517,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194O',
                'category_name' => 'E-commerce Operator',
                'description' => 'TDS on e-commerce sales',
                'rate' => 1.00,
                'type' => 'TDS',
                'applicable_to' => 'Both',
                'code' => 518,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '194Q',
                'category_name' => 'Purchase of Goods',
                'description' => 'TDS on purchase > ₹50L',
                'rate' => 0.10,
                'type' => 'TDS',
                'applicable_to' => 'Company',
                'code' => 519,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '206AB',
                'category_name' => 'Higher TDS for Non-Filers',
                'description' => 'TDS for non-filing taxpayers',
                'rate' => 5.00,
                'type' => 'HIGHER',
                'applicable_to' => 'Both',
                'code' => 520,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
            [
                'section' => '206C',
                'category_name' => 'TCS (Various)',
                'description' => 'Tax collected at source',
                'rate' => null,
                'type' => 'TCS',
                'applicable_to' => 'Both',
                'code' => 521,
                'status' => true,
                'created_at' => now(),
                'created_by' => 1,
            ],
        ];

        $tdsCategories = array_map(function ($category) {
            $category['slug'] = Str::slug($category['category_name']);
            return $category;
        }, $tdsCategories);

        DB::table('default_tds_categories')->upsert(
            $tdsCategories,
            ['slug'],
            ['section', 'category_name', 'description', 'rate', 'type', 'applicable_to', 'code', 'status', 'created_at', 'created_by', 'code']
        );
    }
}
